"""Add whatsapp_template_deliveries table

Revision ID: 2ce0c8575ddb
Revises: 7702486b03d5
Create Date: 2026-09-16 13:06:24.739730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ce0c8575ddb"
down_revision: Union[str, Sequence[str], None] = "7702486b03d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whatsapp_template_deliveries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("to_number", sa.String(), nullable=False),
        sa.Column("template_name", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("parameters", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "provider_response", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_whatsapp_template_deliveries_to_number"),
        "whatsapp_template_deliveries",
        ["to_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_whatsapp_template_deliveries_to_number"),
        table_name="whatsapp_template_deliveries",
    )
    op.drop_table("whatsapp_template_deliveries")
    # ### end Alembic commands ###
