"""Add subscription_deliveries and rename last_sent_date

Revision ID: 3ba72d322a68
Revises: 2ce0c8575ddb
Create Date: 2026-09-16 13:49:27.745220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ba72d322a68"
down_revision: Union[str, Sequence[str], None] = "2ce0c8575ddb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_deliveries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("subscription_id", sa.String(), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "SENT", "FAILED", name="deliverystatus"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["daily_subscriptions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subscription_id", "delivery_date", name="uq_subscription_delivery_date"
        ),
    )
    op.create_index(
        op.f("ix_subscription_deliveries_delivery_date"),
        "subscription_deliveries",
        ["delivery_date"],
        unique=False,
    )
    op.add_column(
        "daily_subscriptions",
        sa.Column("last_successful_delivery_date", sa.Date(), nullable=True),
    )
    op.drop_column("daily_subscriptions", "last_sent_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_subscriptions",
        sa.Column("last_sent_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.drop_column("daily_subscriptions", "last_successful_delivery_date")
    op.drop_index(
        op.f("ix_subscription_deliveries_delivery_date"),
        table_name="subscription_deliveries",
    )
    op.drop_table("subscription_deliveries")
    # ### end Alembic commands ###
