"""Add PROCESSING state

Revision ID: 6217b8a2c8d5
Revises: 86638260fff1
Create Date: 2026-09-16 12:13:56.173641

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6217b8a2c8d5"
down_revision: Union[str, Sequence[str], None] = "86638260fff1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == "postgresql":
        # Disable transaction for ALTER TYPE
        op.execute("COMMIT")
        op.execute("ALTER TYPE reminderstatus ADD VALUE IF NOT EXISTS 'PROCESSING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
