"""Add webhook state fields

Revision ID: 7702486b03d5
Revises: 6217b8a2c8d5
Create Date: 2026-09-16 12:21:28.506329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7702486b03d5"
down_revision: Union[str, Sequence[str], None] = "6217b8a2c8d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM webhook_events")
    bind = op.get_bind()
    if bind.engine.name == "postgresql":
        op.execute(
            "CREATE TYPE webhookstatus AS ENUM ('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED')"
        )
    op.add_column("webhook_events", sa.Column("wa_id", sa.String(), nullable=False))
    op.add_column("webhook_events", sa.Column("text", sa.String(), nullable=False))
    op.add_column(
        "webhook_events",
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED", "PROCESSING", "PROCESSED", "FAILED", name="webhookstatus"
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "webhook_events",
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "webhook_events",
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "webhook_events", sa.Column("failure_reason", sa.String(), nullable=True)
    )
    op.add_column(
        "webhook_events",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webhook_events", "updated_at")
    op.drop_column("webhook_events", "failure_reason")
    op.drop_column("webhook_events", "last_attempt_at")
    op.drop_column("webhook_events", "attempt_count")
    op.drop_column("webhook_events", "status")
    op.drop_column("webhook_events", "text")
    op.drop_column("webhook_events", "wa_id")
    # ### end Alembic commands ###
