"""Add is_summarized to messages

Revision ID: 7c5c5acdda84
Revises: 20f6bf7e1ac0
Create Date: 2026-09-09 16:50:08.902579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c5c5acdda84"
down_revision: Union[str, Sequence[str], None] = "20f6bf7e1ac0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "is_summarized", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "is_summarized")
    # ### end Alembic commands ###
