"""add onboarding_state to users

Revision ID: 9e3232acea9a
Revises: 7c5c5acdda84
Create Date: 2026-09-09 18:08:52.154174

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e3232acea9a"
down_revision: Union[str, Sequence[str], None] = "7c5c5acdda84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    onboarding_state = sa.Enum(
        "WELCOME",
        "LOCATION",
        "OCCUPATION",
        "INTERESTS",
        "COMPLETE",
        name="onboardingstate",
    )
    onboarding_state.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users",
        sa.Column(
            "onboarding_state",
            onboarding_state,
            server_default="WELCOME",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "onboarding_state")
    # ### end Alembic commands ###
