"""Add timezone fields

Revision ID: ce8fe4123810
Revises: e56f90753c09
Create Date: 2026-09-09 14:17:20.312920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce8fe4123810"
down_revision: Union[str, Sequence[str], None] = "e56f90753c09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_subscriptions", sa.Column("last_sent_date", sa.Date(), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("timezone", sa.String(), server_default="UTC", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "timezone")
    op.drop_column("daily_subscriptions", "last_sent_date")
    # ### end Alembic commands ###
