"""Add verification tables and fields

Revision ID: dc01447352d7
Revises: c498f48a21a4
Create Date: 2026-09-16 16:18:10.503902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc01447352d7"
down_revision: Union[str, Sequence[str], None] = "c498f48a21a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_codes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("EMAIL", "WHATSAPP", name="verificationchannel"),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_codes_user_id"),
        "verification_codes",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "email_verified",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "whatsapp_verified",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )

    op.alter_column("users", "email_verified", server_default=sa.text("false"))
    op.alter_column("users", "whatsapp_verified", server_default=sa.text("false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "whatsapp_verified")
    op.drop_column("users", "email_verified")
    op.drop_index(
        op.f("ix_verification_codes_user_id"), table_name="verification_codes"
    )
    op.drop_table("verification_codes")
    # ### end Alembic commands ###
