"""Add latency_ms and error_state to usage_records

Revision ID: e34b351835c2
Revises: b7bb8b7014c5
Create Date: 2026-09-17 11:14:18.402037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e34b351835c2"
down_revision: Union[str, Sequence[str], None] = "b7bb8b7014c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage_records", sa.Column("latency_ms", sa.Float(), nullable=True))
    op.add_column("usage_records", sa.Column("error_state", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_records", "error_state")
    op.drop_column("usage_records", "latency_ms")
    # ### end Alembic commands ###
