"""add independent channel tracking to reminders

Revision ID: ea03c5949489
Revises: 9e3232acea9a
Create Date: 2026-09-10 12:10:30.304190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea03c5949489'
down_revision: Union[str, Sequence[str], None] = '9e3232acea9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('email_status', sa.String(), nullable=True))
    op.add_column('reminders', sa.Column('whatsapp_status', sa.String(), nullable=True))
    op.add_column('reminders', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reminders', sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('reminders', sa.Column('failure_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'failure_reason')
    op.drop_column('reminders', 'attempt_count')
    op.drop_column('reminders', 'last_attempt_at')
    op.drop_column('reminders', 'whatsapp_status')
    op.drop_column('reminders', 'email_status')
    # ### end Alembic commands ###
