"""remove chat_summary from users

Revision ID: f3d995c0d659
Revises: ea03c5949489
Create Date: 2026-09-10 12:20:01.543728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d995c0d659'
down_revision: Union[str, Sequence[str], None] = 'ea03c5949489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_summary', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
